[package]
name = "plotxy"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Hauser <Andreas.Hauser@LMU.de>"]
description = "Commandline tool for plotting TSV/CSV data"
license = "EUPL-1.2"
keywords = ["plot", "command-line", "CLI", "visualization", "TSV", "CSV", "tabular"]
repository = "https://github.com/ahcm/plotxy"

[dependencies]
hex = "0.4.3"
palette = "0.6.1"
plotters = "0.3.4"
polars = { version = "0.25.1", features = ["performant", "lazy"]}
structopt = "0.3.26"
