[package]
name = "plotxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
palette = "0.6.1"
plotters = "0.3.4"
polars = "0.25.1"
structopt = "0.3.26"
